"""init.

Revision ID: 0001
Revises:
Create Date: 2026-09-18 08:56:56.819792
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scenarios",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("skill_group", sa.String(length=32), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("spec_json", sa.JSON(), nullable=False),
        sa.Column("version", sa.String(length=16), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.CheckConstraint("level BETWEEN 1 AND 3", name="ck_scenarios_level"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scenarios", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scenarios_skill_group"), ["skill_group"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "citizen",
                "volunteer",
                "officer",
                name="role",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "display_name",
            sa.String(length=32),
            nullable=False,
            comment="Nickname or code issued by the volunteer; never a legal name",
        ),
        sa.Column("class_id", sa.Uuid(), nullable=True),
        sa.Column(
            "accent_pref",
            sa.Enum(
                "bac",
                "trung",
                "nam",
                name="accent_pref",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column("consent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(display_name) BETWEEN 1 AND 32", name="ck_users_display_name_len"
        ),
        sa.ForeignKeyConstraint(
            ["class_id"], ["classes.id"], name="fk_users_class_id_classes", use_alter=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_class_id"), ["class_id"], unique=False)

    op.create_table(
        "audit",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target", sa.String(length=128), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_actor_id"), ["actor_id"], unique=False)

    op.create_table(
        "classes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("ward_code", sa.String(length=16), nullable=False),
        sa.Column("volunteer_id", sa.Uuid(), nullable=False),
        sa.Column("qr_token", sa.String(length=64), nullable=False),
        sa.Column("qr_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("qr_token_revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["volunteer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("qr_token"),
    )
    with op.batch_alter_table("classes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_classes_volunteer_id"), ["volunteer_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_classes_ward_code"), ["ward_code"], unique=False)

    op.create_table(
        "drills",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("scenario_key", sa.String(length=64), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("red_flags_json", sa.JSON(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("drills", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_drills_scenario_key"), ["scenario_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_drills_user_id"), ["user_id"], unique=False)

    op.create_table(
        "qa_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("question_hash", sa.String(length=64), nullable=False),
        sa.Column("answer_hash", sa.String(length=64), nullable=False),
        sa.Column("citations_json", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("escalated", sa.Boolean(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("qa_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_qa_logs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "screen_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("boxes_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("screen_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_screen_jobs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("scenario_id", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("steps", sa.Integer(), nullable=False),
        sa.Column("mistakes", sa.Integer(), nullable=False),
        sa.Column("hints_used", sa.Integer(), nullable=False),
        sa.Column("duration_s", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_scenario_id"), ["scenario_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "tap",
                "input",
                "hint",
                "error",
                "ask",
                name="event_type",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_session_id"), ["session_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_session_id"))

    op.drop_table("events")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_scenario_id"))

    op.drop_table("sessions")
    with op.batch_alter_table("screen_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_screen_jobs_user_id"))

    op.drop_table("screen_jobs")
    with op.batch_alter_table("qa_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_qa_logs_user_id"))

    op.drop_table("qa_logs")
    with op.batch_alter_table("drills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_drills_user_id"))
        batch_op.drop_index(batch_op.f("ix_drills_scenario_key"))

    op.drop_table("drills")
    with op.batch_alter_table("classes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_classes_ward_code"))
        batch_op.drop_index(batch_op.f("ix_classes_volunteer_id"))

    op.drop_table("classes")
    with op.batch_alter_table("audit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_actor_id"))

    op.drop_table("audit")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_class_id"))

    op.drop_table("users")
    with op.batch_alter_table("scenarios", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scenarios_skill_group"))

    op.drop_table("scenarios")
    # ### end Alembic commands ###
